version: '3.4'

services:
  twitchmanager:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=7037
    ports:
      - "8080:8080"
      - "7037:7037"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - /c/Users/giuse/Downloads/Clips:/data
      - /c/Users/giuse/Downloads/Clips/Download:/clips
      - /c/Users/giuse/Downloads/Clips/Keys:/keys