version: '3.4'

services:
  twitchmanager:
    container_name: twitchmanager
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=7037
    ports:
      - "8080:8080"
      - "7037:7037"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - /F/TwitchManager:/data
      - /F/TwitchManager/Clips/Download:/clips
      - /F/TwitchManager/Clips/Keys:/keys
      - /F/TwitchManager/Clips/appsettings.json:/app/appsettings.json
    networks:
      - twichmanager-network
  db:
    container_name: twitchmanager-db
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin-test
      - MYSQL_DATABASE=twitchmanager
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - twichmanager-network
networks:
  twichmanager-network:
    driver: bridge
volumes:
  db-data: