// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TwitchManager.Data.DbContexts;

#nullable disable

namespace TwitchManager.Migrations.Sqlite
{
    [DbContext(typeof(SqlLiteTwitchManagerDbContext))]
    [Migration("20240306115119_AddClipVote")]
    partial class AddClipVote
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("TwitchManager.Data.Domains.Clip", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BroadcasterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BroadcasterName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClipId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatorName")
                        .HasColumnType("TEXT");

                    b.Property<double>("Duration")
                        .HasColumnType("REAL");

                    b.Property<string>("EmbedUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VodOffset")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BroadcasterId");

                    b.HasIndex("GameId");

                    b.ToTable("Clips", (string)null);
                });

            modelBuilder.Entity("TwitchManager.Data.Domains.ClipVote", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClipId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClipId");

                    b.HasIndex("UserId");

                    b.ToTable("ClipVotes", (string)null);
                });

            modelBuilder.Entity("TwitchManager.Data.Domains.Game", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BoxArtUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("IgdbId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games", (string)null);
                });

            modelBuilder.Entity("TwitchManager.Data.Domains.Streamer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BroadcasterType")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .HasColumnType("TEXT");

                    b.Property<string>("OfflineImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Streamers", (string)null);
                });

            modelBuilder.Entity("TwitchManager.Data.Domains.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("TwitchId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TwitchId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("TwitchManager.Data.Domains.Clip", b =>
                {
                    b.HasOne("TwitchManager.Data.Domains.Streamer", "Streamer")
                        .WithMany("Clips")
                        .HasForeignKey("BroadcasterId");

                    b.HasOne("TwitchManager.Data.Domains.Game", "Game")
                        .WithMany("Clips")
                        .HasForeignKey("GameId");

                    b.Navigation("Game");

                    b.Navigation("Streamer");
                });

            modelBuilder.Entity("TwitchManager.Data.Domains.ClipVote", b =>
                {
                    b.HasOne("TwitchManager.Data.Domains.Clip", "Clip")
                        .WithMany("ClipVotes")
                        .HasForeignKey("ClipId");

                    b.HasOne("TwitchManager.Data.Domains.User", "User")
                        .WithMany("ClipVotes")
                        .HasForeignKey("UserId");

                    b.Navigation("Clip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TwitchManager.Data.Domains.Clip", b =>
                {
                    b.Navigation("ClipVotes");
                });

            modelBuilder.Entity("TwitchManager.Data.Domains.Game", b =>
                {
                    b.Navigation("Clips");
                });

            modelBuilder.Entity("TwitchManager.Data.Domains.Streamer", b =>
                {
                    b.Navigation("Clips");
                });

            modelBuilder.Entity("TwitchManager.Data.Domains.User", b =>
                {
                    b.Navigation("ClipVotes");
                });
#pragma warning restore 612, 618
        }
    }
}
